version: '3'
services:
  web:
    container_name: fitness-web
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - postgres
      - redis
      - webpack
    environment:
      DB_HOST: postgres
      DB_USERNAME: fitness
      DB_PASSWORD: development
      DB_NAME: fitness_development
      REDIS_URL: redis://redis:6379/0

      # webpacker
      WEBPACKER_DEV_SERVER_HOST: webpack
    volumes:
      - './:/app'
    tty: true
    stdin_open: true
  webpack:
    container_name: fitness-webpack
    command: ./bin/webpack-dev-server
    build: .
    ports:
      - '3035:3035'
    environment:
      DB_HOST: postgres
      DB_USERNAME: fitness
      DB_PASSWORD: development
      DB_NAME: fitness_development
      REDIS_URL: redis://redis:6379/0

      # webpack
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
      WEBPACKER_DEV_SERVER_PUBLIC: 0.0.0.0:3035
    volumes:
      - './:/app'
    tty: true
    stdin_open: true
  sidekiq:
    container_name: fitness-sidekiq
    command: ./bin/sidekiq
    build: .
    depends_on:
      - postgres
      - redis
      - web
      - webpack
    environment:
      DB_HOST: postgres
      DB_USERNAME: fitness
      DB_PASSWORD: development
      DB_NAME: fitness_development
      REDIS_URL: redis://redis:6379/0
    volumes:
      - './:/app'
    tty: true
    stdin_open: true
  postgres:
    container_name: fitness-postgres
    image: 'postgres:13.2'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: fitness
      POSTGRES_PASSWORD: development
      POSTGRES_DB: fitness_development
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - './db/development:/var/lib/postgresql/data/pgdata'
  redis:
    container_name: fitness-redis
    image: 'redis:6.0'
    ports:
      - '6379:6379'
