apiVersion: apps/v1
kind: Deployment
metadata:
  name: fitness-web
  labels:
    app: fitness-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fitness-web
  template:
    metadata:
      labels:
        app: fitness-web
    spec:
      containers:
      - name: web
        image: {{ .Values.image }}
        stdin: true
        tty: true
        args:
          - './bin/rails'
          - 'server'
          - '-b'
          - '0.0.0.0'
        env:
          - name: DB_HOST
            value: postgres
          - name: REDIS_URL
            value: redis://redis:6379/0
        volumeMounts:
          - name: fitness-packs
            mountPath: /app/public/packs
      - name: webpack
        image: {{ .Values.image }}
        stdin: true
        tty: true
        args:
          - './bin/webpack-dev-server'
        env:
          - name: DB_HOST
            value: postgres
          - name: REDIS_URL
            value: redis://redis:6379/0
        volumeMounts:
          - name: fitness-packs
            mountPath: /app/public/packs
      volumes:
        - name: fitness-packs
          emptyDir: {}
