apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
