# From https://dev.to/ksaaskil/how-to-deploy-postgres-on-kubernetes-with-skaffold-32fl

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-statefulset
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.2
          env:
            - name: POSTGRES_USER
              value: fitness
            - name: POSTGRES_PASSWORD
              value: development
            - name: POSTGRES_DB
              value: fitness_development
          ports:
            - containerPort: 5432
              name: postgresdb
#          readinessProbe:
#            exec:
#              command:
#                - bash
#                - "-c"
#                - "psql -U$POSTGRES_USER -d$POSTGRES_DB -c 'SELECT 1'"
#            initialDelaySeconds: 15
#            timeoutSeconds: 2
#          livenessProbe:
#            exec:
#              command:
#                - bash
#                - "-c"
#                - "psql -U$POSTGRES_USER -d$POSTGRES_DB -c 'SELECT 1'"
#            initialDelaySeconds: 15
#            timeoutSeconds: 2

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: 5432
      name: postgres
  type: ClusterIP
  selector:
    app: postgres
