apiVersion: v1
kind: Pod
metadata:
  name: fitness-sidekiq
  labels:
    name: fitness-sidekiq
spec:
  containers:
  - name: sidekiq
    image: ghcr.io/noizwaves/fitness
    stdin: true
    tty: true
    command:
     - 'bin/sidekiq'
    env:
      - name: DB_HOST
        value: postgres
      - name: REDIS_URL
        value: redis://redis:6379/0
