apiVersion: v1
kind: Pod
metadata:
  name: fitness-sidekiq
  labels:
    name: fitness-sidekiq
spec:
  containers:
  - name: sidekiq
    image: registry.noizwaves.cloud/fitness
    stdin: true
    tty: true
    command:
     - 'bin/sidekiq'
    env:
      - name: DB_HOST
        value: postgres
      - name: REDIS_URL
        value: redis://redis:6379/0
    volumeMounts:
      - name: home
        mountPath: /home/fitness/app
        subPath: workspace/fitness
  volumes:
    - name: home
      persistentVolumeClaim:
        claimName: home
