apiVersion: v1
kind: Pod
metadata:
  name: fitness-web
  labels:
    name: fitness-web
spec:
  containers:
  - name: fitness-web
    image: ghcr.io/noizwaves/fitness-dev
    stdin: true
    tty: true
    command:
      - './bin/rails'
      - 'server'
      - '-b'
      - '0.0.0.0'
    env:
      - name: DB_HOST
        value: postgres
      - name: REDIS_URL
        value: redis://redis:6379/0
      - name: WEBPACKER_DEV_SERVER_HOST
        value: fitness-webpack