apiVersion: v1
kind: Pod
metadata:
  name: fitness-webpack
  labels:
    app: fitness-webpack
spec:
  containers:
  - name: fitness-webpack
    image: fitness-dev
    stdin: true
    tty: true
    command:
      - './bin/webpack-dev-server'
    env:
      - name: DB_HOST
        value: postgres
      - name: REDIS_URL
        value: redis://redis:6379/0
      - name: WEBPACKER_DEV_SERVER_HOST
        value: 0.0.0.0
      - name: WEBPACKER_DEV_SERVER_PUBLIC
        value: 0.0.0.0:3035

---

apiVersion: v1
kind: Service
metadata:
  name: fitness-webpack
spec:
  ports:
    - port: 3035
      name: webpack
  type: ClusterIP
  selector:
    app: fitness-webpack
