
apiVersion: v1
kind: Pod
metadata:
  name: cloud-shell
  labels:
    name: cloud-shell
spec:
  initContainers:
## not required when running everything as root
#    - name: load-github-private-key
#      image: registry.noizwaves.cloud/cloud-shell
#      command: ["sh", "-c", "cp /root_ssh/* /user_ssh && chown -R 1000:1000 /user_ssh"]
#      volumeMounts:
#        - name: github-ssh-key
#          mountPath: /root_ssh
#          readOnly: true
#        - name: ssh-key
#          mountPath: /user_ssh
## only required for automatic checkout of repo
#    - name: git-clone
#      image: registry.noizwaves.cloud/cloud-shell
#      command: ["git", "clone", "git@github.com:noizwaves/fitness.git", "/root/workspace/fitness"]
#      volumeMounts:
#        - name: workspace
#          mountPath: /root/workspace
#        - name: github-ssh-key
#          mountPath: "/root/.ssh/id_rsa"
#          subPath: id_rsa
#          readOnly: true
#        - name: ssh-known-hosts
#          mountPath: "/root/.ssh/known_hosts"
#          subPath: known_hosts
  containers:
    - name: cloud-shell
      image: registry.noizwaves.cloud/cloud-shell
      command: ["bash", "-c", "while true; do sleep 1; done"]
      workingDir: "/root"
      volumeMounts:
        - name: workspace
          mountPath: /root/workspace
        - name: github-ssh-key
          mountPath: "/root/.ssh/id_rsa"
          subPath: id_rsa
          readOnly: true
        - name: loft-config
          mountPath: "/root/.loft/config.json"
          subPath: config.json
          readOnly: true
        - name: ssh-known-hosts
          mountPath: "/root/.ssh/known_hosts"
          subPath: known_hosts
          readOnly: false
        - name: git-config
          mountPath: "/root/.gitconfig"
          subPath: .gitconfig
          readOnly: false
  dnsPolicy: ClusterFirst
  volumes:
    - name: workspace
      persistentVolumeClaim:
        claimName: workspace
    - name: github-ssh-key
      secret:
        secretName: github-ssh-key
        items:
          - key: ssh-privatekey
            path: id_rsa
            mode: 0600
    - name: loft-config
      secret:
        secretName: loft-config
        items:
          - key: config.json
            path: config.json
            mode: 0600
    - name: ssh-known-hosts
      configMap:
        name: ssh-known-hosts
    - name: git-config
      configMap:
        name: git-config

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteOnce

---

# kubectl create secret generic github-ssh-key --type='kubernetes.io/ssh-auth' --from-file=ssh-privatekey=$HOME/.ssh/id_rsa

# kubectl create configmap ssh-known-hosts --from-file=$HOME/.ssh/known_hosts

# kubectl create configmap git-config --from-file=$HOME/.gitconfig

# kubectl create secret generic loft-config --from-file=$HOME/.loft/config.json
